### ISSUE TITLE
No results in the new version

### ISSUE THREAD

**Issue by FEA-eng** [ceanwang/hfcMystran#4]
When trying to use the new version (with support for stress results added), I get no results at all. Switching to hfcMystran workbench gives those errors:

```
14:33:14  No module named 'hfc_task_result_mechanical'
14:33:14  Traceback (most recent call last):
  File "<string>", line 99, in Initialize
  File "E:\Program Files\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Program Files\FreeCAD 0.21\Mod\hfcMystran\hfcMystranNeuIn.py", line 33, in <module>
    import hfc_task_result_mechanical as trm
  File "E:\Program Files\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
```

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

**Comment by ceanwang** [comment]
Just updated hfcMystranNeuIn.py to use FreeCAD's task panel.
